language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - npm test
deploy:
  provider: npm
  email: "garik.novel@gmail.com"
  skip_cleanup: true
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: TheNovel/rest-api-redux